version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.15.0  # Selecciona la versión de Node.js que necesites
    commands:
      - npm install

  build:
    commands:
      - npm test
